<?php
/**
 * OpenRegister Conversation Entity
 *
 * This file contains the Conversation entity class for the OpenRegister application.
 * Conversations represent AI chat sessions between users and agents.
 *
 * @category Entity
 * @package  OCA\OpenRegister\Db
 *
 * @author    Conduction Development Team <dev@conduction.nl>
 * @copyright 2024 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git_id>
 *
 * @link https://www.OpenRegister.nl
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Db;

use DateTime;
use JsonSerializable;
use OCP\AppFramework\Db\Entity;
use Symfony\Component\Uid\Uuid;

/**
 * Conversation entity class
 *
 * Represents an AI chat conversation within the system.
 * Conversations belong to a user and organisation, use a specific agent,
 * and contain messages.
 *
 * Uses Nextcloud's Entity magic getters/setters for all simple properties.
 * Only methods with custom logic are explicitly defined.
 *
 * @method string|null getUuid()
 * @method void setUuid(?string $uuid)
 * @method string|null getTitle()
 * @method void setTitle(?string $title)
 * @method string|null getUserId()
 * @method void setUserId(?string $userId)
 * @method string|null getOrganisation()
 * @method void setOrganisation(?string $organisation)
 * @method int|null getAgentId()
 * @method void setAgentId(?int $agentId)
 * @method array|null getMetadata()
 * @method void setMetadata(?array $metadata)
 * @method DateTime|null getDeletedAt()
 * @method void setDeletedAt(?DateTime $deletedAt)
 * @method DateTime|null getCreated()
 * @method void setCreated(?DateTime $created)
 * @method DateTime|null getUpdated()
 * @method void setUpdated(?DateTime $updated)
 *
 * @package OCA\OpenRegister\Db
 */
class Conversation extends Entity implements JsonSerializable
{

    /**
     * Unique identifier for the conversation
     *
     * @var string|null UUID of the conversation
     */
    protected ?string $uuid = null;

    /**
     * Title of the conversation (auto-generated by LLM)
     *
     * @var string|null The conversation title
     */
    protected ?string $title = null;

    /**
     * User ID who owns the conversation
     *
     * @var string|null The user ID
     */
    protected ?string $userId = null;

    /**
     * Organisation UUID
     *
     * @var string|null Organisation UUID
     */
    protected ?string $organisation = null;

    /**
     * Agent ID used in this conversation
     *
     * @var integer|null Agent ID
     */
    protected ?int $agentId = null;

    /**
     * Metadata (JSON)
     *
     * Stores additional information like:
     * - summary: string (conversation summary)
     * - token_count: int (total tokens used)
     * - message_count: int (total messages)
     * - last_summary_at: datetime (when last summarized)
     *
     * @var array|null Metadata array
     */
    protected ?array $metadata = null;

    /**
     * Soft delete timestamp
     *
     * @var DateTime|null Deleted at timestamp
     */
    protected ?DateTime $deletedAt = null;

    /**
     * Creation timestamp
     *
     * @var DateTime|null Created timestamp
     */
    protected ?DateTime $created = null;

    /**
     * Last update timestamp
     *
     * @var DateTime|null Updated timestamp
     */
    protected ?DateTime $updated = null;


    /**
     * Conversation constructor
     *
     * Sets up the entity type mappings for proper database handling.
     */
    public function __construct()
    {
        $this->addType('uuid', 'string');
        $this->addType('title', 'string');
        $this->addType('userId', 'string');
        $this->addType('organisation', 'string');
        $this->addType('agentId', 'integer');
        $this->addType('metadata', 'json');
        $this->addType('deletedAt', 'datetime');
        $this->addType('created', 'datetime');
        $this->addType('updated', 'datetime');

    }//end __construct()


    /**
     * Soft delete the conversation
     *
     * @return static Returns self for method chaining
     */
    public function softDelete(): static
    {
        $this->setter(name: 'deletedAt', value: [new DateTime()]);
        return $this;

    }//end softDelete()


    /**
     * Restore soft deleted conversation
     *
     * @return static Returns self for method chaining
     */
    public function restore(): static
    {
        $this->setter(name: 'deletedAt', value: [null]);
        return $this;

    }//end restore()


    /**
     * Serialize the conversation to JSON
     *
     * @return (array|int|null|string)[] Serialized conversation
     *
     * @psalm-return array{
     *     id: int,
     *     uuid: null|string,
     *     title: null|string,
     *     userId: null|string,
     *     organisation: null|string,
     *     agentId: int|null,
     *     metadata: array|null,
     *     deletedAt: null|string,
     *     created: null|string,
     *     updated: null|string
     * }
     */
    public function jsonSerialize(): array
    {
        return [
            'id'           => $this->id,
            'uuid'         => $this->uuid,
            'title'        => $this->title,
            'userId'       => $this->userId,
            'organisation' => $this->organisation,
            'agentId'      => $this->agentId,
            'metadata'     => $this->metadata,
            'deletedAt'    => $this->deletedAt?->format('c'),
            'created'      => $this->created?->format('c'),
            'updated'      => $this->updated?->format('c'),
        ];

    }//end jsonSerialize()


}//end class
