<?php
/**
 * OpenRegister Conversation Entity
 *
 * This file contains the Conversation entity class for the OpenRegister application.
 * Conversations represent AI chat sessions between users and agents.
 *
 * @category Entity
 * @package  OCA\OpenRegister\Db
 *
 * @author    Conduction Development Team <dev@conduction.nl>
 * @copyright 2024 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git_id>
 *
 * @link https://www.OpenRegister.nl
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Db;

use DateTime;
use JsonSerializable;
use OCP\AppFramework\Db\Entity;
use Symfony\Component\Uid\Uuid;

/**
 * Conversation entity class
 *
 * Represents an AI chat conversation within the system.
 * Conversations belong to a user and organisation, use a specific agent,
 * and contain messages.
 *
 * @package OCA\OpenRegister\Db
 */
class Conversation extends Entity implements JsonSerializable
{

    /**
     * Unique identifier for the conversation
     *
     * @var string|null UUID of the conversation
     */
    protected ?string $uuid = null;

    /**
     * Title of the conversation (auto-generated by LLM)
     *
     * @var string|null The conversation title
     */
    protected ?string $title = null;

    /**
     * User ID who owns the conversation
     *
     * @var string|null The user ID
     */
    protected ?string $userId = null;

    /**
     * Organisation UUID
     *
     * @var string|null Organisation UUID
     */
    protected ?string $organisation = null;

    /**
     * Agent ID used in this conversation
     *
     * @var int|null Agent ID
     */
    protected ?int $agentId = null;

    /**
     * Metadata (JSON)
     *
     * Stores additional information like:
     * - summary: string (conversation summary)
     * - token_count: int (total tokens used)
     * - message_count: int (total messages)
     * - last_summary_at: datetime (when last summarized)
     *
     * @var array|null Metadata array
     */
    protected ?array $metadata = null;

    /**
     * Soft delete timestamp
     *
     * @var DateTime|null Deleted at timestamp
     */
    protected ?DateTime $deletedAt = null;

    /**
     * Creation timestamp
     *
     * @var DateTime|null Created timestamp
     */
    protected ?DateTime $created = null;

    /**
     * Last update timestamp
     *
     * @var DateTime|null Updated timestamp
     */
    protected ?DateTime $updated = null;


    /**
     * Conversation constructor
     *
     * Sets up the entity type mappings for proper database handling.
     */
    public function __construct()
    {
        $this->addType('uuid', 'string');
        $this->addType('title', 'string');
        $this->addType('userId', 'string');
        $this->addType('organisation', 'string');
        $this->addType('agentId', 'integer');
        $this->addType('metadata', 'json');
        $this->addType('deletedAt', 'datetime');
        $this->addType('created', 'datetime');
        $this->addType('updated', 'datetime');

    }//end __construct()


    /**
     * Validate UUID format
     *
     * @param string $uuid The UUID to validate
     *
     * @return bool True if UUID format is valid
     */
    public static function isValidUuid(string $uuid): bool
    {
        try {
            Uuid::fromString($uuid);
            return true;
        } catch (\InvalidArgumentException $e) {
            return false;
        }

    }//end isValidUuid()


    /**
     * Get the UUID of the conversation
     *
     * @return string|null The conversation UUID
     */
    public function getUuid(): ?string
    {
        return $this->uuid;

    }//end getUuid()


    /**
     * Set the UUID of the conversation
     *
     * @param string $uuid The UUID
     *
     * @return self
     */
    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;
        return $this;

    }//end setUuid()


    /**
     * Get the title of the conversation
     *
     * @return string|null The conversation title
     */
    public function getTitle(): ?string
    {
        return $this->title;

    }//end getTitle()


    /**
     * Set the title of the conversation
     *
     * @param string|null $title The title
     *
     * @return self
     */
    public function setTitle(?string $title): self
    {
        $this->title = $title;
        return $this;

    }//end setTitle()


    /**
     * Get the user ID
     *
     * @return string|null The user ID
     */
    public function getUserId(): ?string
    {
        return $this->userId;

    }//end getUserId()


    /**
     * Set the user ID
     *
     * @param string $userId The user ID
     *
     * @return self
     */
    public function setUserId(string $userId): self
    {
        $this->userId = $userId;
        return $this;

    }//end setUserId()


    /**
     * Get the organisation ID
     *
     * @return int|null The organisation ID
     */
    public function getOrganisation(): ?string
    {
        return $this->organisation;

    }//end getOrganisation()


    /**
     * Set the organisation UUID
     *
     * @param string|null $organisation The organisation UUID
     *
     * @return self
     */
    public function setOrganisation(?string $organisation): self
    {
        $this->organisation = $organisation;
        return $this;

    }//end setOrganisation()


    /**
     * Get the agent ID
     *
     * @return int|null The agent ID
     */
    public function getAgentId(): ?int
    {
        return $this->agentId;

    }//end getAgentId()


    /**
     * Set the agent ID
     *
     * @param int|null $agentId The agent ID
     *
     * @return self
     */
    public function setAgentId(?int $agentId): self
    {
        $this->agentId = $agentId;
        return $this;

    }//end setAgentId()


    /**
     * Get the metadata
     *
     * @return array|null The metadata array
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;

    }//end getMetadata()


    /**
     * Set the metadata
     *
     * @param array|null $metadata The metadata array
     *
     * @return self
     */
    public function setMetadata(?array $metadata): self
    {
        $this->metadata = $metadata;
        return $this;

    }//end setMetadata()


    /**
     * Get a specific metadata value
     *
     * @param string $key     The metadata key
     * @param mixed  $default Default value if key doesn't exist
     *
     * @return mixed The metadata value
     */
    public function getMetadataValue(string $key, mixed $default = null): mixed
    {
        return $this->metadata[$key] ?? $default;

    }//end getMetadataValue()


    /**
     * Set a specific metadata value
     *
     * @param string $key   The metadata key
     * @param mixed  $value The metadata value
     *
     * @return self
     */
    public function setMetadataValue(string $key, mixed $value): self
    {
        if ($this->metadata === null) {
            $this->metadata = [];
        }
        $this->metadata[$key] = $value;
        return $this;

    }//end setMetadataValue()


    /**
     * Get the deleted at timestamp
     *
     * @return DateTime|null The deleted at timestamp
     */
    public function getDeletedAt(): ?DateTime
    {
        return $this->deletedAt;

    }//end getDeletedAt()


    /**
     * Set the deleted at timestamp
     *
     * @param DateTime|null $deletedAt The deleted at timestamp
     *
     * @return self
     */
    public function setDeletedAt(?DateTime $deletedAt): self
    {
        $this->deletedAt = $deletedAt;
        return $this;

    }//end setDeletedAt()


    /**
     * Check if conversation is soft deleted
     *
     * @return bool True if deleted
     */
    public function isDeleted(): bool
    {
        return $this->deletedAt !== null;

    }//end isDeleted()


    /**
     * Soft delete the conversation
     *
     * @return self
     */
    public function softDelete(): self
    {
        $this->deletedAt = new DateTime();
        return $this;

    }//end softDelete()


    /**
     * Restore soft deleted conversation
     *
     * @return self
     */
    public function restore(): self
    {
        $this->deletedAt = null;
        return $this;

    }//end restore()


    /**
     * Get the creation timestamp
     *
     * @return DateTime|null The creation timestamp
     */
    public function getCreated(): ?DateTime
    {
        return $this->created;

    }//end getCreated()


    /**
     * Set the creation timestamp
     *
     * @param DateTime $created The creation timestamp
     *
     * @return self
     */
    public function setCreated(DateTime $created): self
    {
        $this->created = $created;
        return $this;

    }//end setCreated()


    /**
     * Get the last update timestamp
     *
     * @return DateTime|null The last update timestamp
     */
    public function getUpdated(): ?DateTime
    {
        return $this->updated;

    }//end getUpdated()


    /**
     * Set the last update timestamp
     *
     * @param DateTime $updated The last update timestamp
     *
     * @return self
     */
    public function setUpdated(DateTime $updated): self
    {
        $this->updated = $updated;
        return $this;

    }//end setUpdated()


    /**
     * Serialize the conversation to JSON
     *
     * @return array Serialized conversation
     */
    public function jsonSerialize(): array
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'title' => $this->title,
            'userId' => $this->userId,
            'organisation' => $this->organisation,
            'agentId' => $this->agentId,
            'metadata' => $this->metadata,
            'deletedAt' => $this->deletedAt?->format('c'),
            'created' => $this->created?->format('c'),
            'updated' => $this->updated?->format('c'),
        ];

    }//end jsonSerialize()


}//end class


