<?php

/**
 * PDF report writer.
 *
 * Wraps `HtmlReportWriter` output through Dompdf to produce a single
 * PDF document. Any HTML/CSS that the print stylesheet renders nicely
 * in a browser also renders here — Dompdf is a CSS 2.1-compliant
 * renderer, so the same `@media print` page-break-inside rules apply.
 *
 * Dompdf is sandboxed (no remote URLs, no PHP execution) — the
 * generated bytes are safe to ship to the client or write to Files.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category Service
 * @package  OCA\OpenRegister\Service\Reporting
 *
 * @author  Conduction Development Team <dev@conduction.nl>
 * @license EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @link https://OpenRegister.app
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Service\Reporting;

use Dompdf\Dompdf;
use Dompdf\Options;

/**
 * Render a resolved dashboard as a single PDF document.
 */
class PdfReportWriter
{
    /**
     * Constructor.
     *
     * @param HtmlReportWriter $htmlWriter HTML writer used as the input layer.
     */
    public function __construct(private readonly HtmlReportWriter $htmlWriter)
    {

    }//end __construct()

    /**
     * Render the PDF.
     *
     * @param array<string, mixed>                               $dashboard       Dashboard payload.
     * @param array<int, array{widget: array, data: array|null}> $resolvedWidgets Widget+data tuples.
     *
     * @return string Rendered PDF bytes.
     */
    public function write(array $dashboard, array $resolvedWidgets): string
    {
        $html = $this->htmlWriter->write(dashboard: $dashboard, resolvedWidgets: $resolvedWidgets);

        $options = new Options();
        // No remote stylesheet/image fetches — keeps the renderer hermetic.
        $options->set('isRemoteEnabled', false);
        // PHP execution in templates is disabled by default in 3.x; pin it explicitly.
        $options->set('isPhpEnabled', false);
        $options->set('defaultFont', 'DejaVu Sans');
        $options->set('defaultPaperSize', 'A4');
        $options->set('defaultPaperOrientation', 'portrait');

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html, 'UTF-8');
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $output = $dompdf->output();
        return $output ?? '';

    }//end write()
}//end class
