<?php
/**
 * OpenRegister Migration Version1Date20251105150000
 *
 * Create Conversations and Messages Tables.
 *
 * This migration creates the conversations and messages tables for AI chat functionality,
 * and adds new columns to the agents table for view-based filtering and access control.
 *
 * @category Migration
 * @package  OCA\OpenRegister\Migration
 *
 * @author    Conduction Development Team <dev@conduction.nl>
 * @copyright 2024 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git_id>
 *
 * @link https://www.OpenRegister.nl
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Migration;

use Closure;
use OCP\DB\ISchemaWrapper;
use OCP\DB\Types;
use OCP\Migration\IOutput;
use OCP\Migration\SimpleMigrationStep;

/**
 * Migration to create conversations and messages tables
 *
 * Creates tables for:
 * - Conversations (with org, user, agent, soft delete)
 * - Messages (with role, content, sources)
 * - Updates agents table with view-based filtering and sharing
 *
 * @category Migration
 * @package  OCA\OpenRegister\Migration
 */
class Version1Date20251105150000 extends SimpleMigrationStep
{


    /**
     * Create conversations and messages tables, update agents table
     *
     * @param IOutput $output        Migration output interface
     * @param Closure $schemaClosure Schema closure
     * @param array   $options       Migration options
     *
     * @return ISchemaWrapper|null Updated schema
     */
    public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper
    {
        // @var ISchemaWrapper $schema
        $schema  = $schemaClosure();
        $updated = false;

        // Create conversations table.
        if ($schema->hasTable('openregister_conversations') === false) {
            $output->info(message: '💬 Creating conversations table...');

            $table = $schema->createTable('openregister_conversations');

            // Primary key.
            $table->addColumn(
                    'id',
                    Types::BIGINT,
                    [
                        'autoincrement' => true,
                        'notnull'       => true,
                        'unsigned'      => true,
                    ]
                    );
            $table->setPrimaryKey(['id']);

            // UUID for external reference.
            $table->addColumn(
                    'uuid',
                    Types::STRING,
                    [
                        'notnull' => true,
                        'length'  => 36,
                        'comment' => 'Unique identifier for the conversation',
                    ]
                    );
            $table->addUniqueIndex(['uuid'], 'conversations_uuid_index');

            // Title (auto-generated by LLM).
            $table->addColumn(
                    'title',
                    Types::STRING,
                    [
                        'notnull' => false,
                        'length'  => 255,
                        'default' => null,
                        'comment' => 'Conversation title (auto-generated)',
                    ]
                    );

            // User and organization.
            $table->addColumn(
                    'user_id',
                    Types::STRING,
                    [
                        'notnull' => true,
                        'length'  => 64,
                        'comment' => 'User ID who owns the conversation',
                    ]
                    );

            $table->addColumn(
                    'organisation',
                    Types::STRING,
                    [
                        'notnull' => false,
                        'length'  => 36,
                        'default' => null,
                        'comment' => 'Organisation UUID',
                    ]
                    );

            // Agent reference.
            $table->addColumn(
                    'agent_id',
                    Types::BIGINT,
                    [
                        'notnull'  => false,
                        'unsigned' => true,
                        'default'  => null,
                        'comment'  => 'Agent ID used in this conversation',
                    ]
                    );

            // Metadata (for summaries, token counts, etc.).
            $table->addColumn(
                    'metadata',
                    Types::TEXT,
                    [
                        'notnull' => false,
                        'default' => null,
                        'comment' => 'JSON metadata (summary, token_count, etc.)',
                    ]
                    );

            // Soft delete.
            $table->addColumn(
                    'deleted_at',
                    Types::DATETIME,
                    [
                        'notnull' => false,
                        'default' => null,
                        'comment' => 'Soft delete timestamp',
                    ]
                    );

            // Timestamps.
            $table->addColumn(
                    'created',
                    Types::DATETIME,
                    [
                        'notnull' => true,
                        'comment' => 'Creation timestamp',
                    ]
                    );

            $table->addColumn(
                    'updated',
                    Types::DATETIME,
                    [
                        'notnull' => true,
                        'comment' => 'Last update timestamp',
                    ]
                    );

            // Indexes for performance.
            $table->addIndex(['user_id'], 'conversations_user_id_index');
            $table->addIndex(['organisation'], 'conversations_organisation_index');
            $table->addIndex(['agent_id'], 'conversations_agent_id_index');
            $table->addIndex(['deleted_at'], 'conversations_deleted_at_index');
            $table->addIndex(['created'], 'conversations_created_index');
            $table->addIndex(['user_id', 'organisation', 'deleted_at'], 'conversations_user_org_deleted_index');

            $output->info(message: '✅ Conversations table created');
            $updated = true;
        }//end if

        // Create messages table.
        if ($schema->hasTable('openregister_messages') === false) {
            $output->info(message: '💬 Creating messages table...');

            $table = $schema->createTable('openregister_messages');

            // Primary key.
            $table->addColumn(
                    'id',
                    Types::BIGINT,
                    [
                        'autoincrement' => true,
                        'notnull'       => true,
                        'unsigned'      => true,
                    ]
                    );
            $table->setPrimaryKey(['id']);

            // UUID for external reference.
            $table->addColumn(
                    'uuid',
                    Types::STRING,
                    [
                        'notnull' => true,
                        'length'  => 36,
                        'comment' => 'Unique identifier for the message',
                    ]
                    );
            $table->addUniqueIndex(['uuid'], 'messages_uuid_index');

            // Conversation reference.
            $table->addColumn(
                    'conversation_id',
                    Types::BIGINT,
                    [
                        'notnull'  => true,
                        'unsigned' => true,
                        'comment'  => 'Conversation ID',
                    ]
                    );

            // Message role (user or assistant).
            $table->addColumn(
                    'role',
                    Types::STRING,
                    [
                        'notnull' => true,
                        'length'  => 20,
                        'comment' => 'Message role: user or assistant',
                    ]
                    );

            // Message content.
            $table->addColumn(
                    'content',
                    Types::TEXT,
                    [
                        'notnull' => true,
                        'comment' => 'Message content',
                    ]
                    );

            // RAG sources (for assistant messages).
            $table->addColumn(
                    'sources',
                    Types::TEXT,
                    [
                        'notnull' => false,
                        'default' => null,
                        'comment' => 'JSON array of RAG sources used',
                    ]
                    );

            // Timestamp.
            $table->addColumn(
                    'created',
                    Types::DATETIME,
                    [
                        'notnull' => true,
                        'comment' => 'Creation timestamp',
                    ]
                    );

            // Indexes for performance.
            $table->addIndex(['conversation_id'], 'messages_conversation_id_index');
            $table->addIndex(['conversation_id', 'created'], 'messages_conversation_created_index');
            $table->addIndex(['role'], 'messages_role_index');

            // Foreign key to conversations.
            $table->addForeignKeyConstraint(
                foreignTable: $schema->getTable('openregister_conversations'),
                localColumnNames: ['conversation_id'],
                foreignColumnNames: ['id'],
                options: ['onDelete' => 'CASCADE'],
                'messages_conversation_fk'
            );

            $output->info(message: '✅ Messages table created');
            $updated = true;
        }//end if

        // Update agents table with new columns.
        if ($schema->hasTable('openregister_agents') === true) {
            $output->info(message: '🤖 Updating agents table with new columns...');

            $table = $schema->getTable('openregister_agents');

            // Add views column (JSON array of view UUIDs).
            if ($table->hasColumn('views') === false) {
                $table->addColumn(
                        'views',
                        Types::TEXT,
                        [
                            'notnull' => false,
                            'default' => null,
                            'comment' => 'JSON array of view UUIDs for data scope',
                        ]
                        );
                $output->info(message: '  ✅ Added views column');
                $updated = true;
            }

            // Add search_files column.
            if ($table->hasColumn('search_files') === false) {
                $table->addColumn(
                        'search_files',
                        Types::BOOLEAN,
                        [
                            'notnull' => false,
                            'default' => true,
                            'comment' => 'Whether agent searches in files',
                        ]
                        );
                $output->info(message: '  ✅ Added search_files column');
                $updated = true;
            }

            // Add search_objects column.
            if ($table->hasColumn('search_objects') === false) {
                $table->addColumn(
                        'search_objects',
                        Types::BOOLEAN,
                        [
                            'notnull' => false,
                            'default' => true,
                            'comment' => 'Whether agent searches in objects',
                        ]
                        );
                $output->info(message: '  ✅ Added search_objects column');
                $updated = true;
            }

            // Add is_private column.
            if ($table->hasColumn('is_private') === false) {
                $table->addColumn(
                        'is_private',
                        Types::BOOLEAN,
                        [
                            'notnull' => false,
                            'default' => true,
                            'comment' => 'Whether agent is private (not shared with org)',
                        ]
                        );
                $output->info(message: '  ✅ Added is_private column');
                $updated = true;
            }

            // Add invited_users column (JSON array of user IDs).
            if ($table->hasColumn('invited_users') === false) {
                $table->addColumn(
                        'invited_users',
                        Types::TEXT,
                        [
                            'notnull' => false,
                            'default' => null,
                            'comment' => 'JSON array of user IDs with access to private agent',
                        ]
                        );
                $output->info(message: '  ✅ Added invited_users column');
                $updated = true;
            }

            $output->info(message: '✅ Agents table updated');
        }//end if

        if ($updated === true) {
            return $schema;
        }

        return null;

    }//end changeSchema()


}//end class
