var classes = [
    {
        "name": "OCA\\OpenRegister\\AppInfo\\Application",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [
            "OCP\\AppFramework\\App",
            "OCP\\AppFramework\\Bootstrap\\IBootstrap",
            "OCP\\AppFramework\\Bootstrap\\IRegistrationContext",
            "OCA\\OpenRegister\\Db\\AuditTrailMapper",
            "OCA\\OpenRegister\\Db\\OrganisationMapper",
            "OCA\\OpenRegister\\Service\\OrganisationService",
            "OCA\\OpenRegister\\Db\\SchemaMapper",
            "OCA\\OpenRegister\\Db\\ObjectEntityMapper",
            "OCA\\OpenRegister\\Db\\RegisterMapper",
            "OCA\\OpenRegister\\Service\\Object\\CacheHandler",
            "Twig\\Loader\\ArrayLoader",
            "OCA\\OpenRegister\\Service\\Object\\SaveObject",
            "GuzzleHttp\\Client",
            "OCA\\OpenRegister\\Service\\ConfigurationService",
            "OCA\\OpenRegister\\Service\\Settings\\ValidationOperationsHandler",
            "OCA\\OpenRegister\\Service\\Settings\\SearchBackendHandler",
            "OCA\\OpenRegister\\Service\\Settings\\LlmSettingsHandler",
            "OCA\\OpenRegister\\Service\\Settings\\FileSettingsHandler",
            "OCA\\OpenRegister\\Service\\Settings\\ObjectRetentionHandler",
            "OCA\\OpenRegister\\Service\\Settings\\CacheSettingsHandler",
            "OCA\\OpenRegister\\Service\\Settings\\SolrSettingsHandler",
            "OCA\\OpenRegister\\Service\\Settings\\ConfigurationSettingsHandler",
            "OCA\\OpenRegister\\Service\\SettingsService",
            "OCA\\OpenRegister\\Command\\SolrDebugCommand",
            "OCA\\OpenRegister\\Service\\VectorizationService",
            "OCA\\OpenRegister\\Service\\Chat\\ContextRetrievalHandler",
            "OCA\\OpenRegister\\Service\\Chat\\ToolManagementHandler",
            "OCA\\OpenRegister\\Service\\Chat\\ResponseGenerationHandler",
            "OCA\\OpenRegister\\Service\\Chat\\MessageHistoryHandler",
            "OCA\\OpenRegister\\Service\\Chat\\ConversationManagementHandler",
            "OCA\\OpenRegister\\Service\\Configuration\\GitHubHandler",
            "OCA\\OpenRegister\\Service\\Configuration\\GitLabHandler",
            "OCP\\AppFramework\\Bootstrap\\IBootContext"
        ],
        "parents": [
            "OCP\\AppFramework\\App"
        ],
        "implements": [
            "OCP\\AppFramework\\Bootstrap\\IBootstrap"
        ],
        "lcom": 3,
        "length": 461,
        "vocabulary": 68,
        "volume": 2806.32,
        "difficulty": 27.93,
        "effort": 78389.88,
        "level": 0.04,
        "bugs": 0.94,
        "time": 4355,
        "intelligentContent": 100.46,
        "number_operators": 42,
        "number_operands": 419,
        "number_operators_unique": 8,
        "number_operands_unique": 60,
        "cloc": 262,
        "loc": 469,
        "lloc": 207,
        "mi": 70.06,
        "mIwoC": 24.26,
        "commentWeight": 45.8,
        "kanDefect": 0.58,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 1.14,
        "relativeSystemComplexity": 325.14,
        "totalStructuralComplexity": 972,
        "totalDataComplexity": 3.42,
        "totalSystemComplexity": 975.42,
        "package": " OCA\\OpenRegister\\AppInfo\\",
        "pageRank": 1,
        "afferentCoupling": 0,
        "efferentCoupling": 33,
        "instability": 1,
        "violations": {}
    }
]