<?php

/**
 * OpenRegister WebPushService
 *
 * Imperative Web Push send path (ADR-031 exception — external integration +
 * cryptography). Given a recipient uid and a notification payload, looks up
 * the user's stored Push API subscriptions, builds the aes128gcm-encrypted,
 * VAPID-signed payload via minishlink/web-push, and POSTs it to each push
 * service endpoint. Subscriptions a push service reports gone (HTTP 404 / 410)
 * are pruned via the mapper so dead endpoints are not retried.
 *
 * The VAPID keypair lives in app config (`vapid_public_key` /
 * `vapid_private_key`, generated by `occ openregister:web-push:generate-vapid`).
 * When no keypair is configured the service is a no-op (logs a config warning)
 * rather than throwing — so a missing keypair never breaks an object save.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category Service
 * @package  OCA\OpenRegister\Service\WebPush
 *
 * @author    Conduction Development Team <dev@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * @version GIT: <git-id>
 *
 * @link https://www.OpenRegister.app
 *
 * @spec openspec/changes/openregister-web-push-engine/specs/web-push-delivery/spec.md
 */

declare(strict_types=1);

namespace OCA\OpenRegister\Service\WebPush;

use Minishlink\WebPush\Subscription;
use Minishlink\WebPush\WebPush;
use OCA\OpenRegister\Db\PushSubscriptionMapper;
use OCP\IAppConfig;
use OCP\IURLGenerator;
use Psr\Log\LoggerInterface;

/**
 * Encrypts, signs, and delivers Web Push payloads; prunes gone subscriptions.
 *
 * @spec openspec/changes/openregister-web-push-engine/specs/web-push-delivery/spec.md
 */
class WebPushService {

	/**
	 * App id used for IAppConfig reads.
	 *
	 * @var string
	 */
	private const APP_ID = 'openregister';

	/**
	 * App-config key holding the VAPID public key.
	 *
	 * @var string
	 */
	public const VAPID_PUBLIC_KEY = 'vapid_public_key';

	/**
	 * App-config key holding the VAPID private key.
	 *
	 * @var string
	 */
	public const VAPID_PRIVATE_KEY = 'vapid_private_key';

	/**
	 * Constructor.
	 *
	 * @param PushSubscriptionMapper $subscriptionMapper Subscription store (lookup + prune).
	 * @param IAppConfig $appConfig App-config reader for the VAPID keypair.
	 * @param IURLGenerator $urlGenerator URL generator for the VAPID JWT subject + icon.
	 * @param LoggerInterface $logger Logger for delivery diagnostics.
	 */
	public function __construct(
		private readonly PushSubscriptionMapper $subscriptionMapper,
		private readonly IAppConfig $appConfig,
		private readonly IURLGenerator $urlGenerator,
		private readonly LoggerInterface $logger,
	) {
	}//end __construct()

	/**
	 * Whether a VAPID keypair is configured.
	 *
	 * @return bool True when both public and private keys are present.
	 *
	 * @spec openspec/changes/openregister-web-push-engine/specs/web-push-delivery/spec.md
	 */
	public function isConfigured(): bool {
		$public = $this->appConfig->getValueString(self::APP_ID, self::VAPID_PUBLIC_KEY, '');
		$private = $this->appConfig->getValueString(self::APP_ID, self::VAPID_PRIVATE_KEY, '');

		return ($public !== '' && $private !== '');
	}//end isConfigured()

	/**
	 * Return the configured VAPID public key (or empty string when absent).
	 *
	 * Never returns the private key.
	 *
	 * @return string The base64url VAPID public key, or empty string.
	 *
	 * @spec openspec/changes/openregister-web-push-engine/specs/web-push-delivery/spec.md
	 */
	public function getPublicKey(): string {
		return $this->appConfig->getValueString(self::APP_ID, self::VAPID_PUBLIC_KEY, '');
	}//end getPublicKey()

	/**
	 * Deliver a payload to every active subscription of a recipient.
	 *
	 * Builds one aes128gcm-encrypted, VAPID-signed message per subscription and
	 * POSTs it. On a 404 / 410 Gone response the dead subscription is pruned.
	 *
	 * @param string $uid The recipient Nextcloud uid.
	 * @param array<string, mixed> $payload The notification payload (title, body, icon, tag, url, actions).
	 *
	 * @return int The number of endpoints successfully delivered to.
	 *
	 * @spec openspec/changes/openregister-web-push-engine/specs/web-push-delivery/spec.md
	 */
	public function deliver(string $uid, array $payload): int {
		if ($this->isConfigured() === false) {
			$this->logger->warning(
				'[WebPushService] No VAPID keypair configured — skipping web-push delivery. '
				. 'Run `occ openregister:web-push:generate-vapid`.'
			);
			return 0;
		}

		$subscriptions = $this->subscriptionMapper->findByUser($uid);
		if (count($subscriptions) === 0) {
			return 0;
		}

		$webPush = $this->buildWebPush();
		$json = json_encode($payload);
		if ($json === false) {
			$this->logger->warning('[WebPushService] Failed to JSON-encode push payload.');
			return 0;
		}

		foreach ($subscriptions as $subscription) {
			$sub = Subscription::create(
				[
					'endpoint' => (string)$subscription->getEndpoint(),
					'keys' => [
						'p256dh' => (string)$subscription->getP256dh(),
						'auth' => (string)$subscription->getAuth(),
					],
				]
			);
			$webPush->queueNotification(subscription: $sub, payload: $json);
		}

		$delivered = 0;
		foreach ($webPush->flush() as $report) {
			if ($report->isSuccess() === true) {
				$delivered++;
				continue;
			}

			// Prune endpoints the push service reports gone (404 / 410).
			$statusCode = 0;
			$response = $report->getResponse();
			if ($response !== null) {
				$statusCode = $response->getStatusCode();
			}

			if ($report->isSubscriptionExpired() === true || $statusCode === 404 || $statusCode === 410) {
				$pruned = $this->subscriptionMapper->deleteByEndpoint($report->getEndpoint());
				$this->logger->info(
					sprintf(
						'[WebPushService] Pruned %d gone subscription(s) for endpoint (status %d).',
						$pruned,
						$statusCode
					)
				);
				continue;
			}

			$this->logger->warning(
				sprintf('[WebPushService] Push delivery failed (status %d): %s', $statusCode, $report->getReason())
			);
		}//end foreach

		return $delivered;
	}//end deliver()

	/**
	 * Build a configured WebPush client from the stored VAPID keypair.
	 *
	 * @return WebPush The configured client.
	 *
	 * @spec openspec/changes/openregister-web-push-engine/specs/web-push-delivery/spec.md
	 */
	private function buildWebPush(): WebPush {
		$auth = [
			'VAPID' => [
				'subject' => $this->urlGenerator->getBaseUrl(),
				'publicKey' => $this->appConfig->getValueString(self::APP_ID, self::VAPID_PUBLIC_KEY, ''),
				'privateKey' => $this->appConfig->getValueString(self::APP_ID, self::VAPID_PRIVATE_KEY, ''),
			],
		];

		return new WebPush(auth: $auth);
	}//end buildWebPush()
}//end class
