name: Documentation

on:
  push:
    branches: [documentation]
  pull_request:
    branches: [documentation]

jobs:
  deploy:
    uses: ConductionNL/.github/.github/workflows/documentation.yml@main
    with:
<<<<<<< HEAD
      cname: openregister.conduction.nl
=======
      cname: openregisters.app
>>>>>>> 23880afe22b6f7f799fd5c26a65e169f6b16c773
